global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@provider-validation.com'
  smtp_auth_username: 'alerts@provider-validation.com'
  smtp_auth_password: 'password'

# Templates for alert messages
templates:
  - '/etc/alertmanager/templates/*.tmpl'

# The root route on which each alert arrives
route:
  group_by: ['alertname', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'default-receiver'
  routes:
    # Critical alerts - immediate notification
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 5s
      repeat_interval: 30m
    
    # Warning alerts - less frequent
    - match:
        severity: warning
      receiver: 'warning-alerts'
      group_wait: 30s
      repeat_interval: 2h
    
    # Security alerts - immediate notification to security team
    - match:
        service: provider-validation
        alertname: SecurityEvents
      receiver: 'security-alerts'
      group_wait: 0s
      repeat_interval: 15m

# Inhibition rules allow to mute a set of alerts given that another alert is firing
inhibit_rules:
  # Mute warning alerts if critical alerts are firing
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'service']
  
  # Mute all alerts if the application is down
  - source_match:
      alertname: 'ApplicationDown'
    target_match_re:
      alertname: '.*'
    equal: ['service']

# Receivers
receivers:
  - name: 'default-receiver'
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '#alerts'
        title: 'Provider Validation Alert'
        text: '{{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
        send_resolved: true

  - name: 'critical-alerts'
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '#critical-alerts'
        title: '🚨 CRITICAL: Provider Validation Alert'
        text: |
          {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          *Severity:* {{ .Labels.severity }}
          *Service:* {{ .Labels.service }}
          *Time:* {{ .StartsAt.Format "2006-01-02 15:04:05 UTC" }}
          {{ end }}
        send_resolved: true
    
    email_configs:
      - to: 'admin@provider-validation.com,oncall@provider-validation.com'
        subject: '🚨 CRITICAL: Provider Validation Alert'
        body: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          
          Description: {{ .Annotations.description }}
          
          Severity: {{ .Labels.severity }}
          Service: {{ .Labels.service }}
          Time: {{ .StartsAt.Format "2006-01-02 15:04:05 UTC" }}
          
          {{ end }}

  - name: 'warning-alerts'
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '#alerts'
        title: '⚠️ WARNING: Provider Validation Alert'
        text: |
          {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          *Severity:* {{ .Labels.severity }}
          *Service:* {{ .Labels.service }}
          *Time:* {{ .StartsAt.Format "2006-01-02 15:04:05 UTC" }}
          {{ end }}
        send_resolved: true

  - name: 'security-alerts'
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '#security'
        title: '🔒 SECURITY: Provider Validation Alert'
        text: |
          {{ range .Alerts }}
          *SECURITY ALERT:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          *Severity:* {{ .Labels.severity }}
          *Service:* {{ .Labels.service }}
          *Time:* {{ .StartsAt.Format "2006-01-02 15:04:05 UTC" }}
          {{ end }}
        send_resolved: true
    
    email_configs:
      - to: 'security@provider-validation.com,admin@provider-validation.com'
        subject: '🔒 SECURITY: Provider Validation Alert'
        body: |
          SECURITY ALERT: {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}
          
          {{ range .Alerts }}
          Description: {{ .Annotations.description }}
          
          Severity: {{ .Labels.severity }}
          Service: {{ .Labels.service }}
          Time: {{ .StartsAt.Format "2006-01-02 15:04:05 UTC" }}
          
          IMMEDIATE ACTION REQUIRED
          {{ end }}

  # Webhook receiver for custom integrations
  - name: 'webhook-receiver'
    webhook_configs:
      - url: '${WEBHOOK_URL}'
        send_resolved: true
        http_config:
          basic_auth:
            username: '${WEBHOOK_USERNAME}'
            password: '${WEBHOOK_PASSWORD}'
