# Prometheus configuration for Provider Validation System

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'provider-validation'
    replica: 'prometheus-1'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "rules/*.yml"

# Scrape configuration
scrape_configs:
  # Provider Validation Application
  - job_name: 'provider-validation-app'
    static_configs:
      - targets: ['app:8000']
    metrics_path: '/api/metrics/prometheus'
    scrape_interval: 30s
    scrape_timeout: 10s
    honor_labels: true
    params:
      format: ['prometheus']

  # Provider Validation Health Check
  - job_name: 'provider-validation-health'
    static_configs:
      - targets: ['app:8000']
    metrics_path: '/api/metrics/health'
    scrape_interval: 60s
    scrape_timeout: 5s
    honor_labels: true

  # Provider Validation Dashboard Metrics
  - job_name: 'provider-validation-dashboard'
    static_configs:
      - targets: ['app:8000']
    metrics_path: '/api/metrics/dashboard'
    scrape_interval: 30s
    scrape_timeout: 10s
    honor_labels: true

  # Redis (if exposed)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s
    scrape_timeout: 10s
    metrics_path: '/metrics'

  # PostgreSQL (if using postgres_exporter)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s
    scrape_timeout: 10s

  # Node Exporter (system metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s
    scrape_timeout: 10s

  # cAdvisor (container metrics)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s
    scrape_timeout: 10s

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    scrape_timeout: 10s
